language: nix

os:
  - linux
  - osx

# It's a bit wasteful, in Travis terms, to build each version in a
# separate job, but this allows a clear overview of which individual
# versions are not working, and ultimately we hope to not be building
# often.
env:
  matrix:
    - ATTR=emacs-24-2
    - ATTR=emacs-24-3
    - ATTR=emacs-24-4
    - ATTR=emacs-24-5
    - ATTR=emacs-25-1
    - ATTR=emacs-25-2
    - ATTR=emacs-25-3
    - ATTR=emacs-26-1
    - ATTR=emacs-26-2
    - ATTR=emacs-26-3

matrix:
  exclude:
  - os: osx
    env: ATTR=emacs-24-2

install:
  ./travis-install

script:
  - nix-build -A $ATTR | tee output
  - if [ -n "$CACHIX_SIGNING_KEY" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then cachix push emacs-ci < output; fi
