language: nix

os:
  - linux
  - osx

env:
  matrix:
    - ATTR=emacs-24-3
    - ATTR=emacs-24-4
    - ATTR=emacs-24-5
    - ATTR=emacs-25-1
    - ATTR=emacs-25-2
    - ATTR=emacs-25-3
    - ATTR=emacs-26-1
    - ATTR=emacs-26-2
    - ATTR=emacs-26-3

script: nix-build -A $ATTR
